---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: flake8
        language: python
        language_version: python3.6
        additional_dependencies:
          - unicode-string-literal
      - id: debug-statements
        language: python
        language_version: python3.6

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
        language_version: python3.6
